//* const numbers = [1212,4356,4566,45,455454];

//* const increased = numbers.map(number => ++number)

//* console.log(increased);
//*soru 2//

//* const numbers = [1212,4356,4566,45,"hello","hi",455454];

//* const increased = numbers
//* .filter(sayı => typeof sayı === "number")
//* .map(number => ++ number)
//* .sort((a,b) => a-b) //burada küçükten büyüğe sıralama yaptık


//* let result = confirm ("are you sure?");
//* console.log(result); yes or no questions



//* let ad = prompt("adınızı girin");
//* console.log(`adınız : ${ad} dir`);
//* console.log("adınız : ad + dır");