//* const numbers = [1212,4356,4566,45,455454];

//*const { func } = require("prop-types");

//* const increased = numbers.map(number => ++number)

//* console.log(increased);
//*soru 2//

//* const numbers = [1212,4356,4566,45,"hello","hi",455454];

//* const increased = numbers
//* .filter(sayı => typeof sayı === "number")
//* .map(number => ++ number)
//* .sort((a,b) => a-b) //burada küçükten büyüğe sıralama yaptık


//* let result = confirm ("are you sure?");
//* console.log(result); yes or no questions



//* let ad = prompt("adınızı girin");
//* console.log(`adınız : ${ad} dir`);
//* console.log("adınız : ad + dır");


// var a = 10;
// {
//     let b = 3;
// }
//* console.log("a = " + a);
//* console.log("b =" + b); çalışmaz clg üst blokta olmalı çünkü let ile tanımlanmıştır.

// let age = 30;
// let oldAge = age;
// age = 31;
// console.log(age);
// console.log(oldAge);

//*const language = "Javascript"
//*console.log(language [ language.length - 3 ]); burada languane.lenght undifened bu nedenle -3. teim olan i döner.

//*console.log("505" + (-6) * ("23") );


// function yasKontrolu(yas) {

//     // if (yas > 18) {
//     //   return true;
//     // } else {
//     //   return confirm('Ebeveynlerin izin verdi mi?');

//     return (yas>18)?true: confirm('Ebeveynlerin izin verdi mi?');
//   }
//   console.log(yasKontrolu(10))

//*let age = 30;
//*let oldAge = age;
//*age=31;
//*console.log(age);
//*console.log(oldAge);     primitive values

// const me = {
//   name: "Jonas"
//   age: 30
// /};
// const friend = me;
// friend.age = 27;

// console.log("Friend:", friend);    ikisinde de age 27 çıkar 
// console.log("Me:", me);